Dev
baidu/cloud-provider-baiducloud pull request #81
Opened 2019-05-23 03:54 UTC by wccsama

solve issue#70"指定LB Service的BLB?"

2019-05-23 05:05 UTC, hello2mao requested changes

2019-05-23 05:05 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb.go
> +	// delete double check, check if the services'blb exists every time.
注释不需要说明修改历史，仅说明目前功能即可，下面的日志也可以考虑删除

2019-05-23 05:05 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb.go
> +	if len(serviceAnnotation.LoadBalancerExistId) == 0 { //do not use annotations LoadBalancerExistId
# Pls test：

**Test step：**
- 创建LB Service，不指定EIP和BLB
- console修改BLB的name

**Expect：**
- 服务正常，BLB、EIP不变化

**Result：**
- 重新创建了BLB

2019-05-23 08:50 UTC, wccsama commented on pkg/cloud-provider/load_balancer_blb.go
> +	if len(serviceAnnotation.LoadBalancerExistId) == 0 { //do not use annotations LoadBalancerExistId
already fixed.

2019-05-23 09:50 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb.go
> +		} else if lb == nil { // blb already exist, get info from cloud
用户新建 service 时，annotation 中含有 loadbalancerid 但 没有 exist-id 时，会走到这里，结果是 复用了 BLB 和 eip。这种场景符合预期吗？@hello2mao

2019-05-23 13:42 UTC, hello2mao requested changes

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb.go
> +	glog.V(3).Infof("serviceAnnotation.LoadBalancerId: %s", serviceAnnotation.LoadBalancerId)
这行日志有点多余，实在需要可以level=5，因为线上的过滤等级是4

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb.go
> +		} else if lb == nil { // blb already exist, get info from cloud
这应该算是bug，且这个bug之前就存在，本次需要一起修复。
创建了issue #82  跟踪这个问题的修复

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_eip.go
> +		err = bc.clientSet.Blb().UpdateLoadBalancer(&newLbArg)
UpdateLoadBalancer 方法之前没用过，请确认自测通过。

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer.go
> +		glog.V(3).Infof("testest: %s", lb.Desc)
test日志需要删除

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer.go
> +			err := bc.clientSet.Eip().UnbindEip(&unbindArgs)
这里是先解绑再删除？但是我看注释写的是“just unbind, not delete”

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer.go
> +		if strings.Contains(lb.Desc, "cce_auto_create_eip") {
目前我看到的逻辑是：上面200行，已经判断了如果是用户指定的EIP，则只释放，不删除；那么这边只可能是cce自动创建的EIP，此时直接删除即可。

所以，我的疑问是，为什么要更新blb的desp，加上“cce_auto_create_eip”这个字符创。

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_eip.go
> +		lb.Desc = "cce_auto_create_eip" + lb.Desc
打标记建议使用大家协商好的：“auto generated by cce”

2019-05-23 13:42 UTC, hello2mao commented on pkg/cloud-provider/load_balancer.go
> +
如果是result.LoadBalancerInternalVpc == "true"，那么是否应该直接返回？

2019-05-24 01:50 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb.go
>  	lb, err = bc.waitForLoadBalancer(lb)
下面的 bc.reconcileListeners(service, lb) 函数。当 第二个 创建的 service ，spec.port 与 第一个 service 的 spec.port 相同时，代码里会更新 BLB 的 listener，这个地方是否需要特殊处理一下，新的 service 的 spec.port 不能与前一个相同 ？ @wccsama @hello2mao

2019-05-24 01:55 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb.go
>  	lb, err = bc.waitForLoadBalancer(lb)
两个Service的port可以相同

2019-05-24 01:58 UTC, hello2mao commented
@wccsama 使用文档也辛苦一并更新下，上线后需要同步到百度云文档中心。

2019-05-24 04:47 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb.go
>  	lb, err = bc.waitForLoadBalancer(lb)
port 相同，nodeport 不同。看逻辑，第一个 service 的 listener 会被第二个 覆盖掉，导致第一个 service 不通

2019-05-24 06:06 UTC, wccsama commented on pkg/cloud-provider/load_balancer_blb.go
>  	lb, err = bc.waitForLoadBalancer(lb)
这个确实存在问题，一个BLB理论上可以绑定多个service的。这里需要较大的修改，包括删除BLB时，也应该考虑绑定多service的问题。

2019-05-24 07:07 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb.go
>  	lb, err = bc.waitForLoadBalancer(lb)
> 这个确实存在问题，一个BLB理论上可以绑定多个service的。这里需要较大的修改，包括删除BLB时，也应该考虑绑定多service的问题。

恩，目前不支持一个BLB绑定多个Service，还没有需求，在issue #85 中进行了记录

2019-05-24 08:30 UTC, wccsama commented on pkg/cloud-provider/load_balancer_blb.go
>  	lb, err = bc.waitForLoadBalancer(lb)
目前blb仅支持单个service，用户指定使用过的blb，会报错。删除后，能够正常创建其他service。

2019-05-24 08:57 UTC, hello2mao approved these changes
/lgtm

2019-05-24 08:58 UTC, merged