Fix/issue 87
baidu/cloud-provider-baiducloud pull request #96
Opened 2019-06-19 06:00 UTC by tianyuansun

http://wiki.baidu.com/pages/viewpage.action?pageId=772988186

2019-06-19 06:16 UTC, hello2mao commented
@tianyuansun 
（1）建议去掉内网链接
（2）简单描述解决方案
（3）给出issue地址，类似 FIX #87

2019-06-19 06:24 UTC, hello2mao requested changes

2019-06-19 06:24 UTC, hello2mao commented on docs/controllers/service/examples/nginx-BLB-rs-num.yaml
> +    service.beta.kubernetes.io/cce-load-balancer-rs-num: "1"
change to rs max num?

2019-06-19 06:24 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +	targetRsNum := 50
50建议使用const，DefaultBLBMaxRSNum = 50

2019-06-19 06:24 UTC, hello2mao commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +		if anno.LoadBalancerRsNum < 100 {
这个100和上面的50什么关系

2019-06-19 06:26 UTC, hello2mao commented
> 将需要移出的 rs 权重设置为 0，将上一轮同步后 权重为 0 的 rs 删除

这个优化点在哪里？

2019-06-19 07:40 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +		if anno.LoadBalancerRsNum < 100 {
50 是 默认 rs 数量
100 是 BLB rs 数量的限制

2019-06-19 11:04 UTC, wccsama commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +	if anno.LoadBalancerRsNum > 0 {
这里对anno.LoadBalancerRsNum进行判断是否在合法范围，可以直接判断anno.LoadBalancerRsNum > 0 && anno.LoadBalancerRsNum < 100, log 小于0或者大于100，不用anno.LoadBalancerRsNum嘛。

2019-06-19 11:04 UTC, wccsama commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +
应该先删除绑定在blb的rs，再绑定新的吧。

2019-06-19 11:13 UTC, tianyuansun commented
> > 将需要移出的 rs 权重设置为 0，将上一轮同步后 权重为 0 的 rs 删除
> 
> 这个优化点在哪里？

有可能设置为 0 后，就不会再进入这段逻辑，删不掉。暂时不做

2019-06-20 10:48 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +		if anno.LoadBalancerRsNum < 100 {
fixed

2019-06-20 10:50 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +	if anno.LoadBalancerRsNum > 0 {
在 extracServiceAnnotation 时检查合法性，不合法直接抛出错误，用户可以看到

2019-06-20 11:14 UTC, wccsama commented
/lgtm

2019-06-27 13:30 UTC, tianyuansun commented on docs/controllers/service/examples/nginx-BLB-rs-num.yaml
> +    service.beta.kubernetes.io/cce-load-balancer-rs-num: "1"
changed

2019-06-27 13:30 UTC, tianyuansun commented on pkg/cloud-provider/load_balancer_blb_backend_server.go
> +		if anno.LoadBalancerRsNum < 100 {
fixed

2019-06-28 03:18 UTC, hello2mao approved these changes

2019-07-01 11:34 UTC, merged